<!DOCTYPE html>
<?php 
    $users = new Application_Model_Users();
    $front = Zend_Controller_Front::getInstance();
    $request = $front->getRequest();

    //passing current controller and action for use in view
    $temp_controller = $request->getControllerName();
    $temp_action = $request->getActionName();
?>
<html>
<head>
<title>e-Viation Marketplace</title>
<link rel="stylesheet" href="/css/styles.css" type="text/css" />
<script src="http://code.jquery.com/jquery.js"></script>
<script src="http://code.jquery.com/ui/1.8.14/jquery-ui.js"></script>
<script type="text/javascript" src="js/layout.js"></script>
</head>
<body class="home-page">
<div id="login-window-blur">
    <div id="login-window">
        <a href="#" id="login-close">X</a>
        <form id="login-form" method="post" action="<?php echo($this->url(array('action' => 'login'), NULL, true))?>">
            <img src="/images/login_logo.png" alt="e-VIATION LOGIN"/><br/><br/>
            <label for="usr_email">Email</label><input name="usr_email" id="usr_email"/>
            <label for="usr_password">Password</label><input type="password" name="usr_password" id="usr_password" />
            <input style="display: none;" name="token" value="<?php echo $this->login_token ?>"/>
            <button id="login-submit" type="submit">Login</button>
            <button id="register-button" type="button">Register</button>
            <div id="login-error" style="display: none; width: 350px; position: relative; top: 15px; left: 100px; text-align: center;"></div>
        </form>

        
        
        <form id="register-form" method="post" style="display: none;" action="<?php echo($this->url(array('action' => 'register'), NULL, true)) ?>">
            <img src="/images/register_logo.png" alt="e-VIATION REGISTER"/><br/><br/>
            <input name="usr_fname" id="usr_fname"/><label for="usr_fname">First Name</label><br/><br/>
            <input name="usr_lname" id="usr_lname"/><label for="usr_lname">Last Name</label><br/><br/>
            <input name="usr_email" id="usr_email_register"/><label for="usr_email_register">Email</label><br/><br/>
            <input type="password" name="usr_password" id="usr_password_register"/><label for="usr_password_register">Password</label><br/><br/>
            <input type="password" name="usr_password2" id="usr_password2_register"/><label for="usr_password2_register">Re-enter Password</label><br/><br/>
            <button id="register-submit" type="submit">Register</button><label id="register-error"></label>
        </form>
    </div>
</div>
    
<div id="post-ad-window-blur">
    <div id="post-ad-window">
        <a href="#" id="post-ad-close">X</a>
        
            <div id="post-ad-message"><span>You must be logged in to place an ad.</span></div>
        
        <form id="post-ad-form" enctype="multipart/form-data" method="post" action="<?php echo($this->url(array('action' => 'post-ad'), NULL, true))?>" target="post_target">
            <img src="/images/post_ad_logo.png" alt="e-VIATION PLACE AD"/>
            <br /><br/>
            <div id="post-ad-image-block">
                <br /><br />
                <label for="ads_image1">Image 1</label><input id="ads_image1" name="ads_image1" type="file"/><br /><br />
                <label for="ads_image2">Image 2</label><input id="ads_image2" name="ads_image2" type="file"/><br /><br />
                <label for="ads_image3">Image 3</label><input id="ads_image3" name="ads_image3" type="file"/><br /><br />
                <label for="ads_image4">Image 4</label><input id="ads_image4" name="ads_image4" type="file"/><br /><br />
                <label for="ads_image5">Image 5</label><input id="ads_image5" name="ads_image5" type="file"/>
            </div>
            <input type="hidden" value="<?php echo $this->user['usr_id'] ?>" name="ads_user" />
            <label for="ads_title">Title</label><input style=" width: 297px" name="ads_title" id="ads_title"/><br /><br />
            <label for="ads_price">Price</label><input style="width: 100px" name="ads_price" id="ads_price"/><label style="display: inline; margin-left: 10px;" for="ads_donations_type_id">Donation</label><select style="width: 113px;" name="ads_donations_type_id" id="ads_donations_type_id"><option value="">&nbsp;</option><?php foreach($this->donations_types as $t){ echo '<option value="' . $t['dnt_id_pk'] . '">' . $t['dnt_formatted_value'] . '</option>'; }?></select><br /><br />
            <label for="category-select">Category</label><select id="category-select" style="width: 106px;" name="adc_category"><option value="">&nbsp;</option><?php foreach($this->categories as $c){echo '<option value="' . $c['adc_id_pk'] . '">' . $c['adc_label'] . '</option>';}?></select><label style="display: inline; margin-left: 10px;" for="subcategory-select">-</label><select id="subcategory-select" style="width: 172px;" name="ads_subcategory_id"><option value="">&nbsp;</option><?php foreach($this->subcategories as $s){echo '<option style="display: none;" value="' . $s['asc_id_pk'] . '" data-category-id="' . $s['asc_category_id'] . '">' . $s['asc_label'] . '</option>';}?></select><br /><br />
            <label style="position: relative; bottom: 135px;">Description</label><textarea name="ads_description"></textarea><br /><br />
            
            <button id="post-ad-submit" type="submit">Post this ad</button>
        </form>
        
        <iframe name="post_target" src="#" style="display: none;"></iframe>
    </div>
</div>
    
<div id="logout-window-blur">
    <div id="logout-window">
        <a href="/" id="logout-close">X</a>
        <div id="logout-message"><span>You have successfully logged out.</span></div>
    </div>
</div>
    
<div id="sitemap-window-blur">
    <div id="sitemap-window">
        <a href="#" id="sitemap-close">X</a>
        <img src="/images/sitemap_logo.png" alt="e-VIATION SITEMAP"/>
        <ul id="sitemap">
        <?php
            foreach($this->sitemap as $key => $con) {
                $label = ucwords(implode(' ', explode('-', $key)));
                echo '<li><a href="' . $key . '">' . $label . '</a>';
                if(!empty($con)) {
                    echo '<ul>';
                    foreach($con as $act) {
                        echo '<li><a href="' . $key . '/' . $act['link'] . '">' . $act['label'] . '</a></li>';
                    }
                    echo '</ul>';
                }
                echo '</li>';
            }
        
        ?></ul>
    </div>
</div>
    
<div id="read-more-close">X</div>
    
<div id="read-more"></div>

<div id="photo-viewer">
    <div id="photo-viewer-close">X</div>
    <div id="large-container">
        <div id="large-position">
        </div>
    </div>
    <div id="thumbnails">
        <div class="small-container">
            <div class="small-position">
            </div>
        </div>
        <div class="small-container">
            <div class="small-position">
            </div>
        </div>
        <div class="small-container">
            <div class="small-position">
            </div>
        </div>
        <div class="small-container">
            <div class="small-position">
            </div>
        </div>
        <div class="small-container">
            <div class="small-position">
            </div>
        </div>
    </div>
    
</div>
    
<div style="height: auto !important; height: 100%; min-height: 100%;">
<div style="padding-bottom: 112px;">
	<div class="header-container">
		<div class="header">
			<div class="title">
				<!--image goes here-->
				<img id="logo" style="width: 277px" src="/images/title_home.png" alt=""/>
				
				<div class="top-menu">
                        <?php 
                            if(isset($this->usr_email)) {
                                $user = $users->getAllUsers(array('usr_email' => $this->usr_email));
                                $user = reset($user);
                        ?>
                        <span><a id="logout-link" href="">LOGOUT</a></span>
                        <?php
                                
                            } else {
                        ?>
						<span><a id="login-link" href="#">LOGIN</a></span>
                        <?php } ?>
						<span><a id="post-ad-link" href="#">PLACE AD</a></span>
						<span><a id="sitemap-link" href="#">SITEMAP</a></span>
						<span><a href="#">HELP</a></span>
                </div>
				<form id="search" method="post" action="#">
					<input name="search" style="width: 240px;"/>&nbsp;<button type="submit">SEARCH</button>
				</form>
			</div>
			
			

			
		</div>
	</div>
	
	<div class="main-menu-container">
		<div class="main-menu">
            <?php $main_menu = array(
                    'home' => array('href' => $this->url(array('controller' => 'index'), NULL, true)),
                    'aircraft' => array('href' => $this->url(array('controller' => 'aircraft'), NULL, true)),
                    'project' => array('href' => $this->url(array('controller' => 'project'), NULL, true)),
                    'parts' => array('href' => $this->url(array('controller' => 'parts'), NULL, true)),
                    'everything-else' => array('href' => $this->url(array('controller' => 'everything-else'), NULL, true)),
                    'donations' => array('href' => $this->url(array('controller' => 'donations'), NULL, true)),
                );
            ?>
            <?php
            foreach($main_menu as $key => $link) {
                
                if($key == $temp_controller || ($key == 'home' && $temp_controller == 'index')) {
                    echo('<span><a href="' . $link['href'] . '" class="active">' . strtoupper($key) . '</a></span>');
                } else {
                    echo('<span><a href="' . $link['href'] . '">' . strtoupper($key) . '</a></span>');
                }
            }
            ?>
		</div>
	</div>
	
	<div class="ad-space">
		<div class="ad">
			<img alt="e-viation" src="/images/text_logo.png"/> is the online marketplace that gives back! This is the place to buy, 
            sell and trade while  supporting your favorite charity at the same time. You decide how much of the sale of your item 
            will go toward the charity that you choose. We at <img alt="e-viation" src="/images/text_logo.png"/>.net  pride 
            ourselves in providing our members with a state-of-the-art website that works on all platforms and is very user 
            friendly. We also welcome your input. If you have an idea to make our site better, please let us know (<a href="">suggestions 
            here</a>). The best part is, that membership is free and it only take a minute to join.  All we ask is that you check 
            back often and use our site for all your aviation needs, tell your friends and family. Help us grow!  
            <img alt="e-viation" src="/images/text_logo.png"/>.net will also give back, we will give a portion of any fees we 
            may collect to your charity as well.
            <br /><br />
            Sincerely,<br />
            your <img alt="e-viation" src="/images/text_logo.png"/> Captain
		</div>
	</div>

	
	
	<div class="main">
        <?php echo $this->layout()->content ?>
    </div>
    
</div>
</div>
	
	<div class="main-menu-container" style="margin-top: -112px; font-size: 12px; float: bottom; border-top: 1px solid #ccc;">
    	<div class="main-menu">
			<span><a href="#" class="active">HOME</a></span>
			<span><a href="#">AIRCRAFT</a></span>
			<span><a href="#">PROJECTS</a></span>
			<span><a href="#">PARTS</a></span>
			<span><a href="#">EVERTHING ELSE</a></span>
			<span><a href="#">DONATIONS</a></span>
		</div>
	</div>
	
	<div class="footer">
		Copyright &copy; 2008 e-Viation Marketplace. All Rights Reserved. See our Terms and Services.
	</div>
	
	
</body>
</html>